### ISSUE TITLE
Error in zero_range(range) : x must be length 1 or 2

### ISSUE THREAD

**Issue by bholden7** [ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse#23]
I get this error message after using your codes for Fig 2.3 and 2.4. I have the latest versions of R and RStudio (I get the same message in RStudio as well as 'regular' R). Any ideas?
Thanks.

**Comment by ASKurz** [comment]
Yep. It's due to a recent **ggplot2** update. Older versions allowed users to define the axis limits with notation like `coord_cartesian(xlim = 0:1)`. Now you have to explicitly define the limits more like `coord_cartesian(xlim = c(0, 1))`. I'm slowly going through my books and making this change, but it'll be a while before everything's up to date.

**Comment by bholden7** [comment]
Thanks for this and a million thanks for figures/plots code! Really a tour de force!


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by ASKurz** [comment]
Thank you and you're quite welcome.

**Comment by ASKurz** [comment]
@bholden7, what version of the project were you using? Now that I think about it, most if not all of those issues should have been corrected by the recent 0.2.0 update to the project (https://bookdown.org/content/3686/). When you get a chance, can you confirm that the code in that link works?

**Comment by bholden7** [comment]
Hi. Now I’m using the GitHub version of 3686 and it works perfectly. Thanks so much for the follow up!
If I can bother you with one more issue, which I see is fairly widespread: using brms.
I’ve always had problems running this program and the very next set of graphs rely on output from it but I can’t get it to run. I get a compilation error, specifically: Error in sink(type = "output") : invalid connection
and haven’t found a fix for that. Any ideas? As before, everything is up to date, I’m running a Mac book pro (Catalina), writing the code in Markdown. 
Many thanks, as usual. 

Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by ASKurz** [comment]
Good to hear.

Hmmm, I don't believe I've had that compilation error. Your best guess is to search the Stan Forums. This link seems like a good place to start: [https://discourse.mc-stan.org/t/error-in-sink-type-output-invalid-connection/8911](https://discourse.mc-stan.org/t/error-in-sink-type-output-invalid-connection/8911).
