### ISSUE TITLE
AtBats not used in making Figure 19.7

### ISSUE THREAD

**Issue by petrelharp** [ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse#27]
Thanks for this excellent resource! Minor suggestion:

When making Figure 19.7, there's [a bunch of discussion](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/blob/c45242c50d342d1464fdd1407d84e5057d98f6fe/09.Rmd#L2724) about picking appropriate [values of AtBats](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/blob/c45242c50d342d1464fdd1407d84e5057d98f6fe/09.Rmd#L2732). An `AtBats` column is necessary for `fitted.brmsfit( )` to run, but since we're asking for `scale="linear"`, the value of AtBats is not actually used (changing its values produced identical output). So, the discussion of choosing AtBats here is a bit of a red herring.

A fix would be to say
```
To make our version of Figure 19.7, we’ll have to switch gears from player-specific effects to those specific to positions averaged over individual players. The fitted() approach will probably make this the easiest. To do this, we'll need to specify values for AtBats, but this number won't actually be used, since we're asking for fitted values of the linear predictors ( with scale="linear").
```
and then make the AtBats all equal to 1.

**Comment by ASKurz** [comment]
This is a good catch. Thank you!

**Comment by ASKurz** [comment]
[Done](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/commit/86f2cc5c6230d30cefc07051de57466103a36656). I'll include you in the [Thank-you's section](https://bookdown.org/content/3686/index.html#thank-yous-are-in-order) in the next edition.
