### ISSUE TITLE
Figure 6.1

### ISSUE THREAD

**Issue by Famondir** [ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse#30]
You made a mistake in the code for figure 6.1:

```
d %>% 
  ggplot(aes(x = x, group = group)) +
  
  geom_line(aes(y = dbeta(x, shape1 = shape1, shape2 = shape2)),
            color = "grey50", size = 1.25) +
  scale_x_continuous(breaks = c(0, .5, 1)) +
  coord_cartesian(ylim = 0:3) +
  labs(x = expression(theta),
       y = expression(paste("p(", theta, "|a, b)"))) +
  theme(panel.grid = element_blank()) +
  facet_grid(b~a)
```

It has to be `coord_cartesian(ylim = c(0,3)) +`

Friendly greetings

**Comment by ASKurz** [comment]
You're right. `coord_cartesian()` and the other limits functions are pickier than they used to be. Thanks for pointing this one out! @Famondir, what name should I use when I acknowledge you in the thank you section of the next edition (see [here](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/issues/28))?

**Comment by Famondir** [comment]
My real name (you could use) is Simon Schäfer.

You are doing a realy great work that helps me a lot getting n touch with Bayesian analysis. :)

**Comment by ASKurz** [comment]
Backing up a bit, what version of the ebook are you using, @Famondir? It looks like I've already corrected this in the current version. See [here](https://bookdown.org/content/3686/inferring-a-binomial-probability-via-exact-mathematical-analysis.html#a-description-of-credibilities-the-beta-distribution) for the rendered ebook and [here](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/blob/c1bb0a9460ceb12f7ce921844982ae826fc2d6f0/06.Rmd#L110) for the line of code.

**Comment by Famondir** [comment]
Ah! Well I somehow found the [0.0.5 version](https://bookdown.org/ajkurz/DBDA_recoded/) on my researches. Thanks for the link to the new content. I'll check what you changed till then. I recognise a new color sheme. But you are still pretty explicit (e. g. loo_compare(fit10.1, fit10.2, criterion = "loo") instead of loo(fit10.1, fit10.2) ). Think that's good for learning but I learned the short version in the first hand.^^

**Comment by ASKurz** [comment]
Oh gosh. Yes, a lot has changed since the 0.0.5 version.
