### ISSUE TITLE
Two minor issues in the model comparison chapter (Ch 10)

### ISSUE THREAD

**Issue by OmidGhasemi21** [ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse#34]
Hi Solomon,

I detected some minor issues in the model comparison chapter of the book. They are really minor non-important issues, but I thought they might confuse some readers.

**1. Section: 10.2.2 Solution by grid approximation**

At the end of the grid approximation section, you added the following code to calculate BF:
```
d %>% 
  filter(omega %in% c(.25, .75)) %>% 
  group_by(omega) %>% 
  summarise(sum_posterior = sum(posterior)) %>% 
  mutate(model = c("model_2", "model_1")) %>% 
  select(-omega) %>% 
  spread(key = model, value = sum_posterior) %>% 
  summarise(BF = model_1 / model_2)
#BF
#1  4.68
```

This code gives the correct BF at the end, but if you change the `summarise` function to `mutate` at the final step, you can find a minor mistake.

```
d %>% 
  filter(omega %in% c(.25, .75)) %>% 
  group_by(omega) %>% 
  summarise(sum_posterior = sum(posterior)) %>% 
  mutate(model = c("model_2", "model_1")) %>% 
  select(-omega) %>% 
  spread(key = model, value = sum_posterior) %>% 
  mutate(BF = model_1 / model_2)
# model_1 model_2    BF
#   0.824   0.176  4.68
```

The problem is the order of the model’s names in the mutate function. The posterior probabilities do not sound correct. p(M1|D) = .17. So, you only need to change the order of the model’s names in both mutate functions to match the book:
```
d %>% 
  filter(omega %in% c(.25, .75)) %>% 
  group_by(omega) %>% 
  summarise(sum_posterior = sum(posterior)) %>% 
  mutate(model = c("model_1", "model_2")) %>% 
  select(-omega) %>% 
  spread(key = model, value = sum_posterior) %>% 
  mutate(BF = model_2 / model_1)
# model_1 model_2    BF
#   0.176   0.824  4.68

```

**2. Section: 10.6.1 Priors of different models should be equally informed**

Below the `model_weight` function to compare your three models, you wrote:

```
model_weights(fit10.6, fit10.7, fit10.8, weights = "loo") %>% 
  round(digits = 2)
## fit10.6 fit10.7 fit10.8 
##    0.03    0.49    0.48
```

>The evidence varied a bit by the specific weighting scheme. Across both, the model with the Haldane prior (fit10.8) did arguably the best, but the model with the uniform prior (fit10.9) was clearly in the running. Overall, the evidence for one versus another was weak.

But as you can see, there is no fit10.9 here. I think the text needs to be updated accordingly (`fit10.7`).

Moreover, running the `pp_average` function, I got the following error:
```
pp_average(fit7, fit8, fit9, 
           newdata = nd,
           weights = mw,
           method = "fitted",
           summary = F) %>% 
  as_tibble() %>%
  ggplot(aes(x = V1)) +
  geom_histogram(color = "grey92", fill = "grey67",
                 size = .2, bins = 30) +
  stat_pointintervalh(aes(y = 0), 
                      point_interval = mode_hdi, .width = c(.95, .5))



# Error in "subset" %in% names(list(...)) : object 'nd' not found
```

Hope these help. Thanks.
Omid

**Comment by ASKurz** [comment]
### Section: 10.2.2

This is a really good catch, @OmidGhasemi21. I'm going to follow your example and switch out the `summarise()` code for `mutate()`, which does a nice job making the parts more transparent. I think my confusion may have stemed from how Kruschke computed the BF with m1 / m2 in the previous section, but then switched to m2 / m1, here. I'll add a sentence or two about that, too.

### Section: 10.6.1

Another good catch. I'll change the prose to mention `fit10.7`. However, I didn't get the same error when plotting, like you reported. A little further up in the code toward the end of Section 10.4, I'd already set `nd <- tibble(y = 1)`.
