### ISSUE TITLE
Typo 25.4.1

### ISSUE THREAD

**Issue by t-pollington** [ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse#44]
Within `cens()` we inserted our nominal variable, `cens1`

to

Within `cens()` we inserted our nominal variable, `cen1`

Thanks a lot for the book!

**Comment by ASKurz** [comment]
Hey @t-pollington, could you report this in [Issue #2](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse/issues/2), please?
