### ISSUE TITLE
Will you release this material under an MIT type license?

### ISSUE THREAD

**Issue by davidkane9** [ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse#7]
I would like to use a chapter or two in an intro book I am putting together.

Sorry. Found the license. Thanks for making it public.

**Comment by ASKurz** [comment]
Just give me a proper citation and you're good. 

Kurz, A. S. (2019). *Doing Bayesian Data Analysis in brms and the tidyverse* (Version 0.0.5). http://dx.doi.org/10.5281/zenodo.3585688 [https://bookdown.org/ajkurz/DBDA_recoded/]
